/**
 * Process Manager — spawns and manages commander instances per tenant.
 * Each tenant gets their own Bun subprocess with isolated config/db/port.
 */

import { spawn, type Subprocess } from "bun";
import type Database from "bun:sqlite";
import { getAllTenants, updateTenantStatus, type Tenant } from "./db";
import { mkdirSync, existsSync, writeFileSync, readFileSync } from "fs";
import { resolve, dirname } from "path";

/** Commander root directory (parent of gateway/) */
const COMMANDER_ROOT = resolve(dirname(import.meta.dir), "..");
const APP_ENTRY = resolve(COMMANDER_ROOT, "src/app.ts");

/** Active commander processes */
const processes = new Map<string, Subprocess>();

/** Config template for new tenants */
const CONFIG_TEMPLATE = `# SpaceMolt Commander — Tenant Config
# Auto-generated by gateway. Edit via dashboard settings.

[commander]
brain = "scoring"
evaluation_interval = 60
reassignment_cooldown = 300

[ai]
# User's own LLM API key (encrypted at rest)
# Provider: "ollama", "openai", "anthropic", "gemini", "openrouter", "none"
provider = "none"
api_key = ""
ollama_base_url = "http://localhost:11434"
ollama_model = "qwen3:8b"
tier_order = ["scoring"]
max_latency_ms = 30000
max_tokens = 2048
shadow_mode = false

[fleet]
max_bots = {{MAX_BOTS}}
home_system = ""
home_base = ""
default_storage_mode = "faction_deposit"
min_bot_credits = 5000
max_bot_credits = 150000

[server]
port = {{PORT}}
host = "127.0.0.1"

[cache]
market_ttl_ms = 300000
system_ttl_ms = 3600000

[training]
log_decisions = true
log_snapshots = true
log_episodes = true

[economy]
enable_premium_orders = true

[broadcast]
tick_interval_ms = 3000
`;

export interface ProvisionResult {
  tenantId: string;
  port: number;
  configPath: string;
  dbPath: string;
  logDir: string;
}

/**
 * Provision a new tenant — create directories, config, and database.
 */
export function provisionTenant(
  tenantId: string,
  port: number,
  maxBots: number,
  dataDir = "data/tenants",
): ProvisionResult {
  const tenantDir = resolve(COMMANDER_ROOT, dataDir, tenantId);
  const configPath = resolve(tenantDir, "config.toml");
  const dbPath = resolve(tenantDir, "commander.db");
  const logDir = resolve(tenantDir, "logs");

  // Create directories
  mkdirSync(tenantDir, { recursive: true });
  mkdirSync(logDir, { recursive: true });

  // Generate config from template
  if (!existsSync(configPath)) {
    const config = CONFIG_TEMPLATE
      .replace("{{PORT}}", String(port))
      .replace("{{MAX_BOTS}}", String(maxBots));
    writeFileSync(configPath, config, "utf-8");
  }

  return { tenantId, port, configPath, dbPath, logDir };
}

/**
 * Start a commander process for a tenant.
 */
export function startTenant(tenant: Tenant, db: Database): boolean {
  if (processes.has(tenant.id)) {
    console.log(`[PM] Tenant ${tenant.id} already running`);
    return true;
  }

  if (!existsSync(tenant.configPath)) {
    console.log(`[PM] Config not found: ${tenant.configPath}`);
    updateTenantStatus(db, tenant.id, "error");
    return false;
  }

  try {
    const proc = spawn({
      cmd: [
        "bun", "run", APP_ENTRY,
        "--config", tenant.configPath,
        "--db", tenant.dbPath,
        "--port", String(tenant.port),
        "--log-dir", tenant.logDir,
      ],
      cwd: COMMANDER_ROOT,
      stdout: "pipe",
      stderr: "pipe",
    });

    processes.set(tenant.id, proc);
    updateTenantStatus(db, tenant.id, "running", proc.pid);
    console.log(`[PM] Started tenant ${tenant.id} on port ${tenant.port} (pid ${proc.pid})`);

    // Monitor process exit
    proc.exited.then((code) => {
      console.log(`[PM] Tenant ${tenant.id} exited with code ${code}`);
      processes.delete(tenant.id);
      updateTenantStatus(db, tenant.id, "stopped");
    });

    return true;
  } catch (err) {
    console.error(`[PM] Failed to start tenant ${tenant.id}:`, err);
    updateTenantStatus(db, tenant.id, "error");
    return false;
  }
}

/**
 * Stop a tenant's commander process.
 */
export function stopTenant(tenantId: string, db: Database): void {
  const proc = processes.get(tenantId);
  if (!proc) return;

  proc.kill();
  processes.delete(tenantId);
  updateTenantStatus(db, tenantId, "stopped");
  console.log(`[PM] Stopped tenant ${tenantId}`);
}

/**
 * Restart a tenant's commander process.
 */
export function restartTenant(tenant: Tenant, db: Database): boolean {
  stopTenant(tenant.id, db);
  return startTenant(tenant, db);
}

/**
 * Start all tenants that were running before gateway restart.
 */
export function startAllTenants(db: Database): void {
  const tenants = getAllTenants(db);
  let started = 0;
  for (const tenant of tenants) {
    if (tenant.status === "running" || tenant.status === "stopped") {
      if (startTenant(tenant, db)) started++;
    }
  }
  console.log(`[PM] Auto-started ${started}/${tenants.length} tenant(s)`);
}

/**
 * Stop all running tenant processes (for graceful shutdown).
 */
export function stopAllTenants(db: Database): void {
  for (const [tenantId] of processes) {
    stopTenant(tenantId, db);
  }
}

/**
 * Check health of all running tenants.
 */
export function getHealth(): Array<{ tenantId: string; pid: number; alive: boolean }> {
  const results: Array<{ tenantId: string; pid: number; alive: boolean }> = [];
  for (const [tenantId, proc] of processes) {
    results.push({
      tenantId,
      pid: proc.pid,
      alive: !proc.killed,
    });
  }
  return results;
}

/**
 * Update a tenant's config file (e.g., when user adds API key).
 */
export function updateTenantConfig(
  configPath: string,
  updates: Record<string, string>,
): void {
  let config = readFileSync(configPath, "utf-8");
  for (const [key, value] of Object.entries(updates)) {
    // Simple TOML value replacement — handles basic key = "value" patterns
    const regex = new RegExp(`^(${key.replace(/\./g, "\\.")}\\s*=\\s*).*$`, "m");
    if (regex.test(config)) {
      config = config.replace(regex, `$1"${value}"`);
    }
  }
  writeFileSync(configPath, config, "utf-8");
}
